title: Profile Page
logo: https://github.com/GreenGarnets/profile/blob/master/Assets/profile.jpg?raw=true
description: "e-mail : kmu9842@naver.com<br>github : github.com/GreenGarnets/<br><br>언어를 가리지 않는, 무엇이든 할 수 있는 개발자가 목표인 학생"
google_analytics:
theme: jekyll-theme-minimal
