title: Progile Page
logo: /assets/img/logo.png
description: e-mail : kmu9842@naver.com<br>facebook : https://www.facebook.com/profile.php?id=100003712310012<br>instagram : ggarnet_
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
