title: Profile Page
logo: https://github.com/GreenGarnets/profile/blob/master/Assets/profile.jpg?raw=true
description: "e-mail : kmu9842@naver.com<br>github : github.com/GreenGarnets/<br><br>NAT Games Machine Learning Engineer"
google_analytics:
theme: jekyll-theme-minimal
