title: Profile Page
logo: https://scontent-gmp1-1.xx.fbcdn.net/v/t1.0-9/73513543_1745261242274269_587377515492802560_n.jpg?_nc_cat=102&_nc_ohc=AiMm3f3o2agAX_8isTB&_nc_ht=scontent-gmp1-1.xx&oh=d1f2b0d4d17f775670664dfd35375c3e&oe=5ECCC433
description: e-mail : kmu9842@naver.com<br>
<a href = "https://www.facebook.com/profile.php?id=100003712310012">facebook</a>
<a href = "https://www.instagram.com/ggarnet__/">instagram</a>
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
